### ISSUE TITLE
Inconsistency between Claude's tool_use.input response and NimbleOptions validation

### ISSUE THREAD

**Issue by rubas** [lebrunel/anthropix#11]
When using tools with Claude, there's an inconsistency between the API response format and the required format for subsequent requests. 

Claude returns `tool_use` messages with string keys in the `input` map, but NimbleOptions validation requires atom keys.

```elixir
# Claude Response
%{
  "id" => "toolu_01QPo4pgC42pmLCaU7yZNENq",
  "input" => %{"location" => "City"},
  "name" => "get_weather",
  "type" => "tool_use"
}

# Nimble Validation Requirements 
%{
  content: [
    %{
      id: "toolu_01QPo4pgC42pmLCaU7yZNENq",
      input: %{location: "City"},
      name: "get_weather",
      type: "tool_use"
    }
  ],
  role: "assistant"
}
```

**Comment by lebrunel** [comment]
Thanks. PR looks good. I'm going to take a closer look at client side validation as im not entirely sure nimble options is right here... either way I'll get a release out this week.

**Comment by rubas** [comment]
There is also a similar issue with `tool_result`

```elixir
# Nimble
   # tool_result
    tool_use_id: [type: :string],
    is_error: [type: :boolean],
    content: [type: {:or, [:string, {:list, :map}]}],

# Types
@type content_tool_result() :: %{
    type: String.t(),
    tool_use_id: String.t(),
    content: %{optional(String.t()) => String.t()}
  }
  ```

[Documentation](https://docs.anthropic.com/en/docs/build-with-claude/tool-use#handling-tool-use-and-tool-result-content-blocks) says

> content: The result of the tool, as a string (e.g. "content": "15 degrees") or list of nested content blocks (e.g. "content": [{"type": "text", "text": "15 degrees"}]). These content blocks can use the text or image types.

**Comment by rubas** [comment]
## Tool_Choice
I would also be nice if `Anthropix.chat(client, messages: [..], tool_choice: nil)` would be allowed.

```
{:error,
 %NimbleOptions.ValidationError{
   message: "invalid value for :tool_choice option: expected map, got: nil",
   key: :tool_choice,
   value: nil,
   keys_path: []
 }}
```

**Comment by lebrunel** [comment]
@rubas I've pushed a fix for the atom/string keys issue. My approach here is just to reduce the surface area of what nimble options is validating. Nimble is too brittle a tool for this really, and I think longer term I need to find something else for validating params.

I'm unsure about the tool_choice being nil. I think it's more correct for the option to not be present, tbh.

I'll get a new release published shortly.
