### ISSUE TITLE
Example code result in error

### ISSUE THREAD

**Issue by dsincl12** [lebrunel/anthropix#2]
When I use the example messages I get the following error:

{:error,
 %Anthropix.APIError{
   type: "invalid_request_error",
   message: "messages: Unexpected role \"system\". The Messages API accepts a top-level `system` parameter, not \"system\" as an input message role."
 }}

**Comment by lebrunel** [comment]
Apologies. Just sloppy copy and pasting from my ollama library docs which has the same example.

The error message you get is correct. I'll get the example fixed.
