### ISSUE TITLE
Getting a Stream inside a GenServer

### ISSUE THREAD

**Issue by samrat** [lebrunel/anthropix#3]
Hello 👋 ,

Thanks for this library!

In the docs, it is mentioned

> Because the above approach builds the t:Enumerable.t/0 by calling receive, using this approach inside GenServer callbacks may cause the GenServer to misbehave. Setting the :stream option to a t:pid/0 returns a t:Task.t/0 which will send messages to the specified process.

Does this mean that in order to get a `Stream` inside a GenServer callback, I'll have to recreate the stream? I have a pipeline that takes a stream from Claude and passes LLM-generated text for text-to-speech. A similar pipeline already works for OpenAI(using the `openai` library)

Currently, I see the stream arrive as messages to the process:

```
[info] Ignored message: {#PID<0.885.0>, {:data, %{"content_block" => %{"text" => "", "type" => "text"}, "index" => 0, "type" => "content_block_start"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => "Hello", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " there", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => "!", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " How", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " can", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " I", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " assist", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " you", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => " today", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"text" => "?", "type" => "text_delta"}, "index" => 0, "type" => "content_block_delta"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"index" => 0, "type" => "content_block_stop"}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"delta" => %{"stop_reason" => "end_turn", "stop_sequence" => nil}, "type" => "message_delta", "usage" => %{"output_tokens" => 13}}}}
[info] Ignored message: {#PID<0.885.0>, {:data, %{"type" => "message_stop"}}}
```

**Comment by lebrunel** [comment]
Hi

Yes, if you're working inside a Genserver callback you'll need to be a little creative.

I mean, you could just try using `stream: true` and return a `Stream` back from the `Anthropix.chat` call. It will work fine, but the risk is that whilst the streaming http request is in progress, if other messages are sent to the GenServer mailbox then they may get inadvertently picked up in the receive loop building the Stream, and that's where weird behaviour could occur.

So picking up the messages using `handle_info({pid, {:data, message}})` is the safer way to go.

If you then specifically want a Stream, you'll need to build that yourself.

**Comment by samrat** [comment]
Hm, is this design choice intentional? https://github.com/mgallo/openai.ex works a bit differently in that you get a `Stream` back that you that you can use further?

> I mean, you could just try using stream: true and return a Stream back from the Anthropix.chat call.

I was using `stream: true`(not setting `stream:` to a PID) when I got the "Ignored message" logs I pasted above.

**Comment by lebrunel** [comment]
As for design, the intention is to just be a simple minimal API wrapper. But I'm happy to change things if the ergonomics of using this isn't right.

I'm not too familiar with the openai library, but from glancing at the code, their approach to building the stream isn't all the different to here:

https://github.com/mgallo/openai.ex/blob/main/lib/openai/stream.ex
vs
https://github.com/lebrunel/anthropix/blob/main/lib/anthropix.ex#L419

Only real difference is they use HTTPoison, whereas Anthropix uses Req. I think HTTPoison starts its own process for a streaming request whereas Req doesn't - hence wrapping in a Task. But I don't really understand why one would behave inside a GenServer whilst the other doesn't, as they both ultimately send messages back to the process calling `Stream.resource/3`.

If there's something I'm doing wonky in my approach (totally possible :)), I'm happy to fix that, but I'm a bit lost as to what that might be at the moment.

**Comment by lebrunel** [comment]
Closing this for now as unsure if this is something that can be "fixed".
