### ISSUE TITLE
Prompt caching support

### ISSUE THREAD

**Issue by pedroassumpcao** [lebrunel/anthropix#5]
The `system` param type constraints to `string` instead of also allowing a list of `map` in https://github.com/lebrunel/anthropix/blob/2e4898f1341f3e2b10118df2c8d8f57038df8d6c/lib/anthropix.ex#L296-L299 what differs from the documentation https://docs.anthropic.com/en/api/messages. 

This blocks any work regarding prompt caching https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching where system messages that are good candidates for caching as usually they are fixed.

Here is an example from the docs with system messages containing prompt caching directives:

```json
"system": [
      {
        "type": "text", 
        "text": "You are an AI assistant tasked with analyzing literary works. Your goal is to provide insightful commentary on themes, characters, and writing style.\n"
      },
      {
        "type": "text", 
        "text": "<the entire contents of Pride and Prejudice>",
        "cache_control": {"type": "ephemeral"}
      }
    ]
```

**Comment by lebrunel** [comment]
Thanks for the nudge - this has been on my mental radar for a few weeks.
I'll try and do a new release for this asap.

**Comment by pedroassumpcao** [comment]
@lebrunel I opened a PR that locally works for me as bare minimum for prompt caching support.

**Comment by pedroassumpcao** [comment]
@lebrunel thanks for putting this together.
