### ISSUE TITLE
Error: Binary construction fails during Claude tool-use streaming

### ISSUE THREAD

**Issue by DavidSnoble** [lebrunel/anthropix#8]
### Title
Error: Binary construction fails during Claude tool-use streaming

### Description
When attempting to stream a Claude API request with tool use enabled, the process terminates with a binary construction error. This appears to be related to handling nil values in the stream merger.

#### Error Details
```
** (ArgumentError) construction of binary failed: segment 2 of type 'binary': expected a binary but got: nil
    (anthropix 0.4.0) lib/anthropix.ex:552: anonymous fn/2 in Anthropix.stream_merge/2
```

#### Full Stack Trace
```elixir
** (ArgumentError) construction of binary failed: segment 2 of type 'binary': expected a binary but got: nil
    (anthropix 0.4.0) lib/anthropix.ex:552: anonymous fn/2 in Anthropix.stream_merge/2
    (elixir 1.17.3) lib/kernel.ex:2897: anonymous fn/2 in Kernel.update_in/3
    (elixir 1.17.3) lib/map.ex:957: Map.get_and_update/3
    (elixir 1.17.3) lib/kernel.ex:2897: Kernel.update_in/3
    (elixir 1.17.3) lib/list.ex:1351: List.do_update_at/3
    (elixir 1.17.3) lib/list.ex:1355: List.do_update_at/3
    (elixir 1.17.3) lib/kernel.ex:2897: anonymous fn/2 in Kernel.update_in/3
    (elixir 1.17.3) lib/map.ex:957: Map.get_and_update/3
    (elixir 1.17.3) lib/kernel.ex:2897: Kernel.update_in/3
    (elixir 1.17.3) lib/map.ex:916: Map.update!/3
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (anthropix 0.4.0) lib/anthropix.ex:528: anonymous fn/3 in Anthropix.stream_handler/1
```

#### Environment
- Elixir version: 1.17.3
- anthropix version: 0.4.0
- finch version: 0.19.0

#### Related Documentation
- [Anthropic API - Streaming Request with Tool Use](https://docs.anthropic.com/en/api/messages-streaming#streaming-request-with-tool-use)

### Steps to Reproduce
1. Initiate a streaming request to Claude API with tool use enabled
2. The error occurs during stream merging, specifically in the `Anthropix.stream_merge/2` function

**Comment by DavidSnoble** [comment]
Upon examining the code It seems like the issue occurs from this message chunk
13:09:20.804 [warning] Unhandled chunk type: 
`%{"delta" => %{"partial_json" => "", "type" => "input_json_delta"}, "index" => 1, "type" => `"content_block_delta"}`
When I look at line 552 it is attempting to access delta["text"] which isn't present in this chunk

**Comment by DavidSnoble** [comment]
I have never contributed to a project but I did fix this issue locally to get tool use working!
`  defp stream_merge(res, %{"type" => "content_block_delta", "index" => i, "delta" => %{"type" => "text_delta"} = delta}) do
    update_in(res.body, fn body ->
      update_in(body, ["content"], fn content ->
        List.update_at(content, i, fn block ->
          update_in(block, ["text"], & &1 <> delta["text"])
        end)
      end)
    end)
  end

  defp stream_merge(res, %{"type" => "content_block_delta", "index" => i, "delta" => %{"type" => "input_json_delta"} = delta}) do
    update_in(res.body, fn body ->
      update_in(body, ["content"], fn content ->
        List.update_at(content, i, fn block ->
          update_in(block, ["input"], fn input ->
            case input do
              nil -> %{}
              existing -> existing
            end
          end)
        end)
      end)
    end)
  end`

**Comment by DavidSnoble** [comment]
I opened a pull request for the fix here
https://github.com/lebrunel/anthropix/pull/9

**Comment by lebrunel** [comment]
Thank you for catching this, and doing the work to fix it. I'll take a closer look at the PR in the week. Many thanks 👍🏻

**Comment by lebrunel** [comment]
Thank you for your contribution @DavidSnoble 
v0.4.1 released with your PR merged
